### PR TITLE
add fluid addon

### PR DESCRIPTION
**Pull request by zhujian7**
Fix https://github.com/open-cluster-management-io/ocm/issues/294

### CODE REVIEW

**Comment by qiujian16** [comment]
not sure if makefile is necessary. Seems to me we just need to provide kubectl command in the Reademe?

**Comment by zhujian7** [comment]
> not sure if makefile is necessary. Seems to me we just need to provide kubectl command in the Reademe?

The make command is more convenient for users to deploy the addon, such as replacing the managed cluster name

**Comment by qiujian16** [comment]
but user can use clusterctl to enable addon instead of using make.

**Comment by zhujian7** [comment]
@qiujian16 PTAL

**Comment by qiujian16** [comment]
/approve

nit: could we use `clusterctl addon enable ....` to enable the addon on a cluster :) ?

**Comment by zhujian7** [comment]
> nit: could we use `clusterctl addon enable ....` to enable the addon on a cluster :) ?

@qiujian16 fixed, PTAL

**Pull request merged**
